---

- name: config nginx
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'nginx/jormougand.nginx.conf',dest: '/etc/nginx/conf.d/jormougand.nginx.conf' }
    - { src: 'nginx/sql.conf',dest: '/etc/nginx/sql.conf' }
    - { src: 'nginx/app.conf',dest: '/etc/nginx/conf.d' }
    - { src: 'nginx/software.conf',dest: '/etc/nginx/conf.d' }

- name: config nginx
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '755'
  with_items:
    - { src: 'nginx/start_nginx.sh',dest: '/opt/bigtoe/start_nginx.sh' }
  ignore_errors: True

- name: restart docker nginx
  shell: ./start_nginx.sh
  args:
    chdir: /opt/bigtoe
  ignore_errors: True

- meta: flush_handlers

- name: copy service config file
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'serviceConfig/arcee_captured.json',dest: '/home/{{ansible_user}}/platformTG/arcee_captured/latest/arcee.json' }
    - { src: 'serviceConfig/arcee_registered.json',dest: '/home/{{ansible_user}}/platformTG/arcee_registered/latest/arcee.json' }
    - { src: 'serviceConfig/archimedes-config.txt',dest: '/home/{{ansible_user}}/platformTG/archimedes/latest/config/config.txt' }
    - { src: 'serviceConfig/athena-dbservice_config.txt',dest: '/home/{{ansible_user}}/platformTG/athena/latest/athenadir/config/dbservice_config.txt' }
    - { src: 'serviceConfig/export_config.txt',dest: '/home/{{ansible_user}}/platformTG/athena/latest/athenadir/config/export_config.txt' }
    - { src: 'serviceConfig/export_sql_to_excel_config.txt',dest: '/home/{{ansible_user}}/platformTG/athena/latest/athenadir/config/export_sql_to_excel_config.txt' }
    - { src: 'serviceConfig/export_sql_to_excel_with_param_beyond_db_config.txt',dest: '/home/{{ansible_user}}/platformTG/athena/latest/athenadir/config/export_sql_to_excel_with_param_beyond_db_config.txt' }
    - { src: 'serviceConfig/platform_sync_gb_config.txt',dest: '/home/{{ansible_user}}/platformTG/athena/latest/athenadir/config/platform_sync_gb_config.txt' }
    - { src: 'serviceConfig/platform_sync_pvg_config.txt',dest: '/home/{{ansible_user}}/platformTG/athena/latest/athenadir/config/platform_sync_pvg_config.txt' }
    - { src: 'serviceConfig/bultgang-config.json',dest: '/home/{{ansible_user}}/platformTG/bultgang/latest/config.json' }
    - { src: 'serviceConfig/croatia_config.txt',dest: '/home/{{ansible_user}}/platformTG/croatia/latest/config/croatia_config.txt' }
    - { src: 'serviceConfig/isdconfig.txt',dest: '/home/{{ansible_user}}/platformTG/isd/latest/tmp/isdconfig.txt' }
    - { src: 'serviceConfig/k2s-config.json',dest: '/home/{{ansible_user}}/platformTG/k2s/latest/config.json' }
    - { src: 'serviceConfig/kronos_config.txt',dest: '/home/{{ansible_user}}/platformTG/kronos/latest/config/config.txt' }
    - { src: 'serviceConfig/loki-production.json',dest: '/home/{{ansible_user}}/platformTG/loki/latest/config/production.json' }
    - { src: 'serviceConfig/loki-default.json',dest: '/home/{{ansible_user}}/platformTG/loki/latest/config/default.json' }
    - { src: 'serviceConfig/odin-config.json',dest: '/home/{{ansible_user}}/platformTG/odin/latest/configs/config.json' }
    - { src: 'serviceConfig/pse_config.json',dest: '/home/{{ansible_user}}/platformTG/pse/latest/config/config.json' }
    - { src: 'serviceConfig/sax_vehicle_application.yml',dest: '/home/{{ansible_user}}/platformTG/sax_vehicle/latest/config/application.yml' }
    - { src: 'serviceConfig/themis_config.json',dest: '/home/{{ansible_user}}/platformTG/themis/latest/config.json' }
    - { src: 'serviceConfig/capture.properties',dest: '/home/{{ansible_user}}/platformTG/ullr/capture/capture.properties' }
    - { src: 'serviceConfig/warn.properties',dest: '/home/{{ansible_user}}/platformTG/ullr/warn/warn.properties' }

- name: copy loki template file
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'serviceConfig/lokitemplates/dahua.json',dest: '/home/{{ansible_user}}/platformTG/loki/latest/config/templates/dahua.json' }
    - { src: 'serviceConfig/lokitemplates/dc84.json',dest: '/home/{{ansible_user}}/platformTG/loki/latest/config/templates/dc84.json' }
    - { src: 'serviceConfig/lokitemplates/haikangsdk.json',dest: '/home/{{ansible_user}}/platformTG/loki/latest/config/templates/haikangsdk.json' }
    - { src: 'serviceConfig/lokitemplates/huawei.json',dest: '/home/{{ansible_user}}/platformTG/loki/latest/config/templates/huawei.json' }
    - { src: 'serviceConfig/lokitemplates/huimu.json',dest: '/home/{{ansible_user}}/platformTG/loki/latest/config/templates/huimu.json' }
    - { src: 'serviceConfig/lokitemplates/importer.json',dest: '/home/{{ansible_user}}/platformTG/loki/latest/config/templates/importer.json' }
    - { src: 'serviceConfig/lokitemplates/importer_libraF.json',dest: '/home/{{ansible_user}}/platformTG/loki/latest/config/templates/importer_libraF.json' }
    - { src: 'serviceConfig/lokitemplates/link_video.json',dest: '/home/{{ansible_user}}/platformTG/loki/latest/config/templates/link_video.json' }
