---

- name: config nginx
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'nginx/jormougand.nginx.conf',dest: '/etc/nginx/conf.d/jormougand.nginx.conf' }
    - { src: 'nginx/sql.conf',dest: '/etc/nginx/sql.conf' }
    - { src: 'nginx/software.conf',dest: '/etc/nginx/conf.d' }
  notify:
    - nginx reload

- meta: flush_handlers

- name: copy service config file 
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'serviceConfig/arcee_captured.json',dest: '/home/{{ansible_user}}/platformTG/arcee_captured/latest/arcee.json' }
    - { src: 'serviceConfig/arcee_registered.json',dest: '/home/{{ansible_user}}/platformTG/arcee_registered/latest/arcee.json' }
    - { src: 'serviceConfig/croatia_config.txt',dest: '/home/{{ansible_user}}/platformTG/croatia/latest/config/croatia_config.txt' }
    - { src: 'serviceConfig/isdconfig.txt',dest: '/home/{{ansible_user}}/platformTG/isd/latest/tmp/isdconfig.txt' }
    - { src: 'serviceConfig/k2s-config.json',dest: '/home/{{ansible_user}}/platformTG/k2s/latest/config.json' }
    - { src: 'serviceConfig/loki-production.json',dest: '/home/{{ansible_user}}/platformTG/loki/latest/config/production.json' }
    - { src: 'serviceConfig/odin-config.json',dest: '/home/{{ansible_user}}/platformTG/odin/latest/configs/config.json' }

- name: copy loki template file
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'serviceConfig/lokitemplates/dahua.json',dest: '/home/{{ansible_user}}/platformTG/loki/latest/config/templates/dahua.json' }
    - { src: 'serviceConfig/lokitemplates/haikangsdk.json',dest: '/home/{{ansible_user}}/platformTG/loki/latest/config/templates/haikangsdk.json' }
    - { src: 'serviceConfig/lokitemplates/huawei.json',dest: '/home/{{ansible_user}}/platformTG/loki/latest/config/templates/huawei.json' }
    - { src: 'serviceConfig/lokitemplates/huimu.json',dest: '/home/{{ansible_user}}/platformTG/loki/latest/config/templates/huimu.json' }
    - { src: 'serviceConfig/lokitemplates/importer.json',dest: '/home/{{ansible_user}}/platformTG/loki/latest/config/templates/importer.json' }
    - { src: 'serviceConfig/lokitemplates/importer_libraF.json',dest: '/home/{{ansible_user}}/platformTG/loki/latest/config/templates/importer_libraF.json' }
    - { src: 'serviceConfig/lokitemplates/link_video.json',dest: '/home/{{ansible_user}}/platformTG/loki/latest/config/templates/link_video.json' }
    - { src: 'serviceConfig/config.js',dest: '/home/{{ansible_user}}/platformTG/jormougand/latest/config.js' }

- name: config sax and jormougand for personfile
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'serviceConfig/loki-production-personalfile.json',dest: '/home/{{ansible_user}}/platformTG/loki/latest/config/production.json' }
    - { src: 'serviceConfig/odin-config_personfile.json',dest: '/home/{{ansible_user}}/platformTG/odin/latest/configs/config.json' }
  when: personfile == true

- name: config sax and jormougand for no personfile
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'serviceConfig/loki-production.json',dest: '/home/{{ansible_user}}/platformTG/loki/latest/config/production.json' }
  when: personfile == false
