---

- name: load docker images
  shell: find images -name *.img|xargs -i docker load -i {};
  args:
    chdir: /home/{{ansible_user}}/platformTG/run

- name: run mserver
  shell: bash run.sh
  args:
    chdir: /home/{{ansible_user}}/platformTG/run/mserver

- name: run mcluster
  shell: bash run.sh
  args:
    chdir: /home/{{ansible_user}}/platformTG/run/mcluster
