---

- name: untar bigtoe ---->/opt/ remote take long time
  unarchive:
    src: package/bigtoe_DeepCloud-{{deepcloud_version}}.tar.gz
    dest: /opt/
    creates: /opt/bigtoe/bigtoe-tools

- name: delete bigtoe_DeepCloud-{{deepcloud_version}}.tar.gz
  file:
    path: /etc/ansible/roles/common/files/package/bigtoe_DeepCloud-{{deepcloud_version}}.tar.gz
    state: absent
  tags: [delete]


- name: change bigtoe install scripts
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '755'
  with_items:
    - { src: 'conf/bigtoe/fse-tools.sh',dest: '/opt/bigtoe/fse-tools.sh'}
    - { src: 'conf/bigtoe/install_web.sh',dest: '/opt/bigtoe/install_web.sh'}



- command: test -f /etc/bigtoe/flags/init_done
  register: result
  ignore_errors: true

# TODO 重复执行判断
- name: execute install_web.sh
  shell: bash install_web.sh
  args:
    chdir: /opt/bigtoe
  when: result|failed

#- include: updateImporter.yml
#- include: updateKafka.yml
