---

#- name: untar bigtoe ---->/opt/ remote take long time
#  unarchive:
#    src: package/bigtoe_DeepCloud-{{deepcloud_version}}-all.tar.gz
#    dest: /opt/
#    creates: /opt/bigtoe/bigtoe-tools

- name: change bigtoe install scripts
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '755'
  with_items:
    - { src: 'conf/bigtoe/fse-tools.sh',dest: '/opt/bigtoe/fse-tools.sh'}
    - { src: 'conf/bigtoe/install_web.sh',dest: '/opt/bigtoe/install_web.sh'}
    - { src: 'conf/bigtoe/config_params.sh',dest: '/opt/bigtoe/config_params.sh'}



- command: test -f /etc/bigtoe/flags/init_done
  register: result
  ignore_errors: true

# TODO 重复执行判断
- name: execute install_web.sh
  shell: bash install_web.sh
  args:
    chdir: /opt/bigtoe
  when: result|failed


#- include: updateNginx.yml
#- include: updateKafka.yml
#- include: updateLink.yml
#- include: updateImporter.yml
#- include: updateVSE.yml


#- name: change ip for config file and change template file
#  template:
#    src: '{{ item.src }}'
#    dest: '{{ item.dest }}'
#  with_items:
#    - { src: 'conf/bigtoe/DeepEngine-{{bigtoe_version}}.ini',dest: '/opt/bigtoe/DeepEngine-{{bigtoe_version}}.ini' }
#    - { src: 'conf/bigtoe/DeepEngine-{{bigtoe_version}}.ini-template',dest: '/opt/bigtoe/src/var/www/bigtoe/tmpl/configs/DeepEngine-{{bigtoe_version}}' }
