---

- name: update nginx version num for safe
  shell: sed -i "s/# server_tokens off;/server_tokens off;/g" nginx.conf
  args:
    chdir: /etc/nginx/

- name: update nginx ----> nginx-1.16.0 for safe
  copy:
    src: '{{ item.src }}' 
    dest: '{{ item.dest }}' 
    backup: yes 
  with_items:
    - { src: 'conf/nginx/nginx',dest: '/usr/sbin/nginx' } 


- name: remove some no used .so file 
  file:
    dest: '{{ item.dest }}' 
    state: absent
  with_items:
    - { dest: '/etc/nginx/modules-enabled/50-mod-http-subs-filter.conf' } 
    - { dest: '/etc/nginx/modules-enabled/50-mod-http-upstream-fair.conf' } 

- name: update nginx modules
  copy:
    src: '{{ item.src }}' 
    dest: '{{ item.dest }}' 
  with_items:
    - { src: 'conf/nginx/modules',dest: '/usr/lib/nginx/' } 
