---


- name: copy image to /opt/bigtoe
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}' 
  with_items:
    - { src: 'package/importer-1.3.6.img',dest: '/opt/bigtoe/' } 

- name: load importer-1.3.6 image
  shell: docker load -i importer-1.3.6.img
  args:
    chdir: /opt/bigtoe


- name: load importer-1.3.6 image
  shell: sed -i "s#dockerhub.deepglint.com/deepvideo/importer:1.3.3.1_vse#dockerhub.deepglint.com/deepvideo/importer:1.3.6#g" /opt/bigtoe/pkg/k8s-conf/deepengine/link/link-configmap.yaml;kubectl replace -f /opt/bigtoe/pkg/k8s-conf/deepengine/link/link-configmap.yaml;kubectl delete pods -n link --all
