---


- name: copy image and config file to /opt/bigtoe/pkg/docker-images
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}' 
  with_items:
    - { src: 'package/importer-1.3.6.tar',dest: '/opt/bigtoe/pkg/docker-images' }
