---


- name: copy image and config file to /opt/bigtoe/pkg/docker-images
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'package/importer-1.3.6_sp3.tar',dest: '/opt/bigtoe/pkg/x86_64/docker-images' }
    - { src: 'package/hm_importer-0.12.5.tar',dest: '/opt/bigtoe/pkg/x86_64/docker-images' }
    - { src: 'package/hw_importer-0.8.0.tar',dest: '/opt/bigtoe/pkg/x86_64/docker-images' }
    - { src: 'package/dc84_sdk-0.1.0.tar',dest: '/opt/bigtoe/pkg/x86_64/docker-images' }

- name: load dc84_sdk-0.1.0
  shell: docker load -i /opt/bigtoe/pkg/docker-images/dc84_sdk-0.1.0.tar
  args:
    chdir: /opt/bigtoe/pkg/x86_64/docker-images
  when: update == True


#- name: restart link
#  shell: kubectl apply -f link-configmap.yaml ; kubectl delete pods -n link --all
#  args:
#    chdir: /opt/bigtoe/pkg/k8s-conf/deepengine/link
#  when: update == True
