---


- name: install dependence_software
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    #- nginx
    - openssh-server
    - vim
    - ifenslave
      #    - ntp
    - tree
    - cpufrequtils
    - htop
    - nmon
    - zip
    - rar
    - unrar
    - libbz2-dev
    - bc
    - coreutils
    - open-iscsi
    - multipath-tools
    - default-jre
    - openjdk-8-jdk
      #    - nfs-common
    - libltdl7
    - nload
    - iotop
    - supervisor
    - lrzsz
    - unzip
  tags: [node]
