---

- include: prepare/mount.yml
  tags: [mount_check]
  when: not update


- include: prepare/directory_prepare.yml
  tags: [directory]
  when: not update

- include: prepare/software_prepare.yml
  tags: [software]
  when: not update

- name: Check vsftpd
  command: dpkg-query -l vsftpd
  register: vsftpd_check
  ignore_errors: True
  tags: [ftp]

- include: software/ftp.yml
  when: vsftpd_check.stderr.find('no packages found') != -1
  tags: [ftp]

- include: software/install_software.yml
  when: not update

- name: Check docker
  command: dpkg-query -l docker
  register: docker_check
  ignore_errors: True
  tags: [docker]

- include: install/installdocker.yml
  when: docker_check.stderr.find('no packages found') != -1
  tags: [docker]

- include: install/installnginx.yml
  tags: [nginx]

- name: Check k8s
  command: dpkg-query -l kubeadm
  register: k8s_check
  ignore_errors: True
  tags: [k8s]

- include: install/installk8s.yml
  when: k8s_check.stderr.find('no packages found') != -1
  tags: [k8s]

- name: Check k8smaster init
  shell: kubectl get node
  register: init_check
  ignore_errors: True
  tags: [init]

- include: install/installk8smaster.yml
  when: init_check.stderr.find('did you specify the right host') != -1
  tags: [init]

- include: install/installhelm.yml
  tags: [k8s, helm]

- include: install/installTG.yml

- name: Check SSH Version
  command: ssh -V
  register: SSH_check
  ignore_errors: True


- name: update SSH
  #debug: msg={{SSH_check}}
  include: software/updateSSH.yml
  when: SSH_check.stderr.find('OpenSSH_8.0p1') == -1
