server:
  port: 8084
  tomcat:
    uri-encoding: UTF-8
    max-connections: 5000
    min-spare-threads: 100
    accept-count: 5000
    max-threads: 10000
  connection-timeout: 5000


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://{{groups.db[0]}}:5432/sax_vehicle
    username: postgres
    password: Zstvgcs@9102
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false

cache:
  query:
    size: 100000
    thread: 3

