---
## General
zookeeper_version: 3.5.6

## Service options

# Owner
zookeeper_user: zookeeper
zookeeper_group: zookeeper

# start on boot
zookeeper_service_enabled: 'yes'
# current state: started, stopped
zookeeper_service_state: started

# Files & Paths
zookeeper_data_dir: /platformData/zookeeper
zookeeper_log_dir: /platformData/zookeeper/log
zookeeper_install_path: /usr/local/zookeeper
zookeeper_conf_dir: "{{ zookeeper_install_path }}/conf"


# Connection properties
# Deprecated
client_port: 2181
# Deprecated
init_limit: 5
# Deprecated
sync_limit: 2
# Deprecated
tick_time: 2000
zookeeper_client_port: "{{ client_port }}"
zookeeper_init_limit: "{{ init_limit }}"
zookeeper_sync_limit: "{{ sync_limit }}"
zookeeper_tick_time: "{{ tick_time }}"

zookeeper_autopurge_purgeInterval: 0
zookeeper_autopurge_snapRetainCount: 10

# Java options
zookeeper_jmx_enabled: false
zookeeper_jmx_port: 1099
zookeeper_java_opts: "-Djava.net.preferIPv4Stack=true"

# Rolling file appender setttings
zookeeper_rolling_log_file_max_size: 10MB
zookeeper_max_rolling_log_file_count: 10

# List of dict (i.e. {zookeeper_hosts:[{host:,id:},{host:,id:},...]})
zookeeper_hosts: "
    {%- set ips = [] %}
    {%- for host in groups['zookeeper_servers'] %}
    {{- ips.append(dict(id=loop.index, host=host, ip=hostvars[host]['ansible_default_ipv4'].address)) }}
    {%- endfor %}
    {{- ips -}}"
# Dict of ENV settings to be written into the (optional) conf/zookeeper-env.sh
zookeeper_env: {}

# Controls Zookeeper myid generation
zookeeper_force_myid: true

zookeeper_force_reinstall: false

#
# You can add more zookeper config options using zookeeper_config_map
#
# zookeeper_config_map:
#  - key: traceFile
#    value: zoo-trace.log
