---

- name: load fse docker img
  shell: ./load_image.sh
  args:
    chdir: /home/{{ansible_user}}/platformTG/fse/fse-{{fse_version}}

- name: start fse
#  shell: ./run_runtime.sh
  shell: ./run_black-nocard.sh;./run_runtime-nocard.sh
  args:
    chdir: /home/{{ansible_user}}/platformTG/fse/fse-{{fse_version}}

- name: sleep 35 second for fse start successfully
  pause: seconds=35

- name: create cluster fse db
  shell: ./run_cluster-nocard.sh
  args:
    chdir: /home/{{ansible_user}}/platformTG/fse/fse-{{fse_version}}
