---

- name: copy 
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '{{ item.mode }}'
  with_items:
    - { src: 'bigtoe-tools', dest: '/opt/bigtoe', mode: 755 }

- name: node bigtoe init
  shell: bash install_minion.sh;
  args:
    chdir: /opt/bigtoe
    creates: /etc/bigtoe/flags/init_done

#- name: join cluster
#  shell: "{{hostvars[hostvars[inventory_hostname]['groups']['master'][0]]['token']}}"
#  args:
#    creates: /etc/bigtoe/flags/master_ip
#  when: cluster == true
#
#- name: install_minion command
#  shell:  echo "{{groups.master[0]}}" >/etc/bigtoe/flags/master_ip
#  when: cluster == true

#  debug: var={{token}}
#  debug: var=hostvars[hostvars[inventory_hostname]['groups']['master'][0]]['token']
#  debug: var=hostvars[inventory_hostname]['groups']['master']
