---

#- name: config nginx
#  template:
#    src: '{{ item.src }}' 
#    dest: '{{ item.dest }}' 
#  with_items:
#    - { src: 'nginx/jormougand.nginx.conf',dest: '/etc/nginx/conf.d/jormougand.nginx.conf' }
#    - { src: 'nginx/sql.conf',dest: '/etc/nginx/sql.conf' }
#  notify:
#    - nginx reload
#
- meta: flush_handlers

- name: copy service config file 
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'serviceConfig/arcee_captured.json',dest: '/home/{{ansible_user}}/platformTG/arcee_captured/latest/arcee.json' }
    - { src: 'serviceConfig/arcee_registered.json',dest: '/home/{{ansible_user}}/platformTG/arcee_registered/latest/arcee.json' }
    - { src: 'serviceConfig/saxconfig.txt',dest: '/home/{{ansible_user}}/platformTG/sax/latest/tmp/saxconfig.txt' }
