---

- name: make softlink for {{platformPath}} ---> /home/{{ansible_user}}/{{platformPath}}
  file:
    path: /home/{{ansible_user}}/{{platformPath}}
    src: '{{platformPath}}'
    state: link


- name: mkdir for {{platformPath}}
  file:
    path: /home/{{ansible_user}}{{platformPath}}/{{ item }}
    state: directory
    recurse: yes
#    force: true
  with_items:
    - redis
    - kafka
    - logs
    - weedfs
    - http_server
    - loki/upload/assets/images
    - loki/upload/civilpackages
#  ignore_errors: True

#- name: make softlink for fse-cloud-sata
#  file:
#    path: /fse-sata
#    src: '/platformData/fse-sata'
#    state: link
#    force: true
#  ignore_errors: True

#- name: make softlink for fse-cloud-ssd
#  file:
#    path: /fse-ssd
#    src: '/platformData/fse-ssd'
#    state: link
# #   force: true
#  ignore_errors: True

- name: make softlink for /platformData/loki/upload/videos
  file:
    path: /platformData/loki/upload/videos
    src: /data/bigtoe/upload-videos
    state: link
    force: true

- name: copy logo and sound file to /platformData/loki
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'rulevoice',dest: '/platformData/loki/upload' }
    - { src: 'vehiclerulevoice',dest: '/platformData/loki/upload' }
    - { src: 'audio',dest: '/platformData/loki/upload' }
    - { src: 'syslogo.png', dest: '/platformData/loki/upload/assets/images' }
    - { src: 'logo.png', dest: '/platformData/loki/upload/assets/images/logo.png' }

- name: copy kafka_tool file to /usr/bin
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '{{ item.mode }}'
  with_items:
    - { src: 'package/kafka_tool_20190726', dest: '/usr/bin', mode: 755 }

- name: execute  fse directory prepare
  shell: bash fse-tools.sh init-dir
  args:
    chdir: /opt/bigtoe
