---

- name: make softlink for {{platformPath}} ---> /home/{{ansible_user}}/{{platformPath}}
  file:
    path: /home/{{ansible_user}}/{{platformPath}}
    src: '{{platformPath}}'
    state: link


- name: mkdir for {{platformPath}}
  file:
    path: /home/{{ansible_user}}{{platformPath}}/{{ item }}
    state: directory
    recurse: yes
  #with_items: [redis,kafka,logs,fse,weedfs,http_server,loki/upload/assets/images]
  with_items:
    - redis
    - kafka
    - logs
    - fse
    - weedfs
    - http_server
    - loki/upload/assets/images
    - loki/upload/civilpackages

- name: make softlink for /platformData/loki/upload/videos
  file:
    path: /platformData/loki/upload/videos
    src: /data/bigtoe/upload-videos
    state: link
    force: true

- name: copy logo and sound file to /platformData/loki
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'rulevoice',dest: '/platformData/loki/upload' }
    - { src: 'syslogo.png', dest: '/platformData/loki/upload/assets/images' }
    - { src: 'logo.png', dest: '/platformData/loki/upload/assets/images/logo.png' }

- name: copy kafka_tool file to /usr/bin
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '{{ item.mode }}'
  with_items:
    - { src: 'package/kafka_tool_20190726', dest: '/usr/bin', mode: 755 }
