---

- name: untar k8s package for k8s install
  unarchive:
    src: package/k8s.tgz
    dest: /opt/
    creates: /opt/k8s

- name: install k8s
  shell: dpkg -i *.deb
  args:
    chdir: /opt/k8s

- name: load k8s base images
  shell: find /etc/ansible/roles/common/files/package/base -name "*.tar"|xargs -i docker load -i {};

- name: turn off swap
  shell: swapoff -a

- name: delete swap config from /etc/fstab
  lineinfile:
    regexp: 'swap(.*)'
    dest: /etc/fstab
    state: absent
