---

- name: create server.properties file
  template: src=server.properties.j2 dest={{ sansible_kafka_install_dir }}/kafka/config/server.properties mode=0644

- name: Setup environment config
  become: yes
  become_user: "{{ sansible_kafka_user }}"
  template:
    dest: "{{ sansible_kafka_install_dir }}/etc/environment"
    mode: 0644
    src: environment.j2
  notify:
    - restart kafka

- name: Create log4j.properties
  become: yes
  become_user: "{{ sansible_kafka_user }}"
  template:
    dest: "{{ sansible_kafka_install_dir }}/etc/log4j.properties"
    mode: 0644
    src: log4j.properties.j2
  notify:
    - restart kafka


- name: Flush handlers to ensure Kafka is up to date
  meta: flush_handlers


- name: Ensure Kafka is running
  become: yes
  service:
    enabled: yes
    name: kafka
    state: started

- name: Wait for Kafka port
  wait_for:
    port: "{{ sansible_kafka_port }}"
    state: started
    timeout: "{{ sansible_kafka_wait_for_kafka_port }}"
