
- name: config mutischeduler
  template:
    src: '{{ item.src }}' 
    dest: '{{ item.dest }}' 
  with_items:
    - { src: 'conf/mutischeduler/config.json',dest: '/home/{{ansible_user}}/platformTG/run/mutischeduler-1.0.0' }

- name: load mutischeduler image
  shell: bash load_mutischeduler-1.0.0.sh
  args:
    chdir: /home/{{ansible_user}}/platformTG/run/mutischeduler-1.0.0

- name: run mutischeduler
  shell: bash run_image.sh
  args:
    chdir: /home/{{ansible_user}}/platformTG/run/mutischeduler-1.0.0
