---

#- name: untar platformTG to ---->>> /home/{{ansible_user}}/platformTG local
#  unarchive:
#    src: package/platformTG.tgz
#    dest: /home/{{ansible_user}}
#    creates: /home/{{ansible_user}}/platformTG/VERSION
#  connection: local

- name: untar platformTG to ---->>> /home/{{ansible_user}}/platformTG remote
  unarchive:
    src: package/platformTG.tgz
    dest: /home/{{ansible_user}}
    creates: /home/{{ansible_user}}/platformTG

- name: copy tools to /platformData/http_server
  copy:
    src: package/tools.zip
    dest: /platformData/http_server
