---

- name: untar platformTG to ---->>> /home/{{ansible_user}}/platformTG
  unarchive:
    src: package/platformTG.tgz
    dest: /home/{{ansible_user}}
    creates: /opt/software_package

- include: installMserverMcluster.yml

- include: installFse.yml
  apply:
    tags: [fse]
  tags: [always]
