---

- include: bigtoe/bigtoe_check.yml
  tags: [bigtoe]
  when: not update

- include: bigtoe/bigtoe.yml
  tags: [bigtoe]
  when: not update

- include: prepare/directory_prepare.yml
  when: not update

- include: prepare/software_prepare.yml
  tags: [postgresql]
  when: not update

- name: Check vsftpd
  command: dpkg-query -l vsftpd
  register: vsftpd_check
  ignore_errors: True

- include_tasks:
    file: software/ftp.yml
    apply:
      tags:
      - ftp
  when: vsftpd_check.stderr.find('no packages found') != -1
  tags: [always]


- include: software/install_software.yml
  when: not update
- include: install/installTG.yml

- name: Check SSH Version
  command: ssh -V
  register: SSH_check
  ignore_errors: True

- name: update SSH
  #debug: msg={{SSH_check}}
  include: software/updateSSH.yml
  when: SSH_check.stderr.find('OpenSSH_8.0p1') == -1
