---

- name: Check OS Version 
  fail: msg="OS {{ ansible_lsb.description }} is not correct" 
  when:
    - ansible_distribution != "Ubuntu"
#   - ansible_lsb.description != "Ubuntu 14.04.5 LTS"
    - ansible_lsb.description != "Ubuntu 16.04.5 LTS"                                                                 

- include: bigtoe/bigtoe_check.yml
  tags: [bigtoe]

- include: bigtoe/bigtoe.yml 
  tags: [bigtoe]

- include: prepare/directory_prepare.yml

- include: prepare/software_prepare.yml
  tags: [postgresql]

- name: Check vsftpd
  command: dpkg-query -l vsftpd
  register: vsftpd_check
  ignore_errors: True

- include_tasks:
    file: software/ftp.yml 
    apply:
      tags:
      - ftp
  when: vsftpd_check.stderr.find('no packages found') != -1
  tags: [always]


- include: software/install_software.yml

- name: Check SSH Version
  command: ssh -V
  register: SSH_check
  ignore_errors: True
   
   
- name: update SSH
  #debug: msg={{SSH_check}}
  include: software/updateSSH.yml
  when: SSH_check.stderr.find('OpenSSH_8.0p1') == -1


- include: install/installTG.yml

- include: software/postgresql.yml
  tags: [postgresql]


  #- include: install/installMutischeduler.yml
  #  tags: [hhh]


#- name: Check supervisor
#  command: dpkg-query -l supervisor 
#  register: supervisor_check
#  ignore_errors: True
#   
#   
#- name: Install supervisor
#  apt:
#    name: supervisor 
#    state: present
#  when: supervisor_check.stderr.find('no packages found') != -1
