---

- include: prepare/mount.yml
  tags: [mount_check]
  when: not update

- include: bigtoe/bigtoe.yml
  tags: [bigtoe]
  when: not update

- include: prepare/directory_prepare.yml
  tags: [directory]
  when: not update

- include: prepare/software_prepare.yml
  tags: [software]
  when: not update

- name: Check vsftpd
  command: dpkg-query -l vsftpd
  register: vsftpd_check
  ignore_errors: True
  tags: [ftp]

- include: software/ftp.yml
  when: vsftpd_check.stderr.find('no packages found') != -1
  tags: [ftp]

- include: software/install_software.yml
  when: not update

- include: software/ntpdate.yml

- include: install/installTG.yml

- name: Check SSH Version
  command: ssh -V
  register: SSH_check
  ignore_errors: True

- name: change ip for config file and change template file
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'conf/bigtoe/DeepEngine-{{bigtoe_version}}.ini',dest: '/opt/bigtoe/DeepEngine-{{bigtoe_version}}.ini'}
#    - { src: 'conf/bigtoe/DeepEngine-{{bigtoe_version}}.ini-template',dest: '/opt/bigtoe/src/var/www/bigtoe/tmpl/configs/DeepEngine-{{bigtoe_version}}'}

- include: bigtoe/updateImporter.yml

- name: update SSH
  #debug: msg={{SSH_check}}
  include: software/updateSSH.yml
  when: SSH_check.stderr.find('OpenSSH_8.0p1') == -1
