apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    qcloud-app: godeye
  name: godeye
  namespace: {{.Values.namespace}}
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      qcloud-app: godeye
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        qcloud-app: godeye
    spec:
      containers:
      - args:
        - -stderrthreshold=0
        - -v=2
        - -logtostderr=1
        - -modulename=godeye
        - -redisaddr={{.Values.redis.service_name}}.{{.Values.redis.namespace}}:{{.Values.redis.port}}
        - -redispasswd={{.Values.redis.password}}
        - -iotcc=false
        - -importerport=80
        command:
        - ./godeye
        image: ccr.ccs.tencentyun.com/face_cloud/godeye:{{.Values.godeyeimageTag}}
        imagePullPolicy: IfNotPresent
        name: godeye
        resources:
          limits:
            cpu: 2000m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        workingDir: /godeye
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      serviceAccountName: ""
      terminationGracePeriodSeconds: 30
