---
- command: test -f /etc/bigtoe/flags/init_done
  register: result
  ignore_errors: true


- name: execute install bigtoe master
  shell: ./install_master.sh DeepEngine-{{bigtoe_version}}.ini
  args:
    chdir: /opt/bigtoe
  when: result|failed


- name: get cluster token
  shell: kubeadm token create --print-join-command | sudo tee /etc/bigtoe/join-token
  register: jointoken
  when: cluster == true


- name: setting facet
  set_fact:
    token: "{{jointoken.stdout}}"
  when: cluster == true


- name: copy vse init.val and public.val ----> /opt/bigtoe/pkg/k8s-conf/deepengine/vse/config/template
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'conf/bigtoe/init.val',dest: '/opt/bigtoe/pkg/k8s-conf/deepengine/vse/config/template/init.val' }
    - { src: 'conf/bigtoe/public.val',dest: '/opt/bigtoe/pkg/k8s-conf/deepengine/vse/config/template/public.val' }
  when: not update


- name: execute config_params
  shell: ./config_params.sh
  args:
    chdir: /opt/bigtoe
  when: not update

- name: make template take effect
  shell: ./bigtoe-tools deploy deepengine-vse;./bigtoe-tools deploy deepengine-fse
  args:
    chdir: /opt/bigtoe
